### ISSUE TITLE
Babel-runtime not found error

### ISSUE THREAD

**Issue by bzd2000** [SpoonX/swan-example-client#44]
When a create a new project from scratch with swan setup, the i get following error:

resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/home/bzd/swan-example/swan-example-client/node_modules/require-relative/index.js:30:17)
    at resolve (/home/bzd/swan-example/swan-example-client/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/home/bzd/swan-example/swan-example-client/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /home/bzd/swan-example/swan-example-client/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/home/bzd/swan-example/swan-example-client/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/home/bzd/swan-example/swan-example-client/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/home/bzd/swan-example/swan-example-client/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/bzd/swan-example/swan-example-client/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at DestroyableTransform._transform (/home/bzd/swan-example/swan-example-client/node_modules/gulp-babel/index.js:37:20)
    at DestroyableTransform.Transform._read (/home/bzd/swan-example/swan-example-client/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/bzd/swan-example/swan-example-client/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/bzd/swan-example/swan-example-client/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/home/bzd/swan-example/swan-example-client/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/home/bzd/swan-example/swan-example-client/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at DestroyableTransform.ondata (/home/bzd/swan-example/swan-example-client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:546:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7) code: 'MODULE_NOT_FOUND' } babel-runtime
/home/bzd/swan-example/swan-example-client/node_modules/gulp-util/lib/PluginError.js:45
        self[prop] = options.error[prop];

When I downgrade  "babel-preset-es2015-loose": "^8.0.0" to     "babel-preset-es2015-loose": "^7.0.0"
the problem is gone.

But it doesn't seem to be a good solution to downgrade the package.

**Comment by RWOverdijk** [comment]
Like I said on gitter, I agree with you. We'll look into this.

**Comment by RWOverdijk** [comment]
@bas080 Could you take this one on?

**Comment by bas080** [comment]
I have reproduced the issue. It appears that the serve gulp task is giving this error. What the solution would be is not yet clear to me. Maybe @doktordirk can share his insights as he knows most about the spoonx-tools.
